import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".remotion/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Vercel Workflow compiler during typecheck/build.
    "src/app/.well-known/workflow/**",
  ]),
]);

export default eslintConfig;
